### ISSUE TITLE
Suggestion: "Calling mechanic..." message for broken rides improvements

### ISSUE THREAD

**Issue by mwilmott2013** [TheEntireCommunistManifesto/OpenRCT2#16]
Situation when a mechanic is called for a broken ride:

-When you did not hire any mechanics: you see at the repair tab of a ride "Calling mechanic...". This is strange, because there is no mechanic to call. Suggestion: in this situation let it display: "No mechanics hired yet." (So, here it should check IF any mechanics are hired. When not, it should display this)

-When you have many broken rides, but not enough mechanics (available); you see at the repair tab of a ride "Calling mechanic..." again. This should be something like: "No mechanic available to repair this ride at the moment."
(So, here it should check IF any mechanics are hired, when yes, it should check if any mechanics have the status "walking" and display this message, as that is the only status of a mechanic when he is not (heading) for repairing a ride or doing an inspection.)

When mechanics are hired and at least one has the status "walking", "Calling mechanic..." should just be displayed.

Link to Original: https://github.com/OpenRCT2/OpenRCT2/issues/5340

**Comment by mwilmott2013** [comment]
The string appears in the window where the Force a Breakdown button is, the maintenance option for a ride.  If I recall, its windows/ride.c.

**Comment by Voytella** [comment]
The case for RIDE_MECHANIC_STATUS_CALLING in /Sources/windows/ride.c will be modified to include a check for the number of available mechanics, and the stringID will be changed accordingly.

**Comment by mwilmott2013** [comment]
In data/language, there are 4 files in which we need to create new strings:

ja-JP.txt
nb-NO.txt
en-GB.txt
en_US.txt

**Comment by mwilmott2013** [comment]
My build now displays "No mechanics hired."  We just need to figure out how to get the thing to tell us if any mechanics are available or not.

**Comment by mwilmott2013** [comment]
To add the strings, go into the data\language file(s), and at the end of the string declarations, write two new ones.  Be sure to mimic the style of the calling mechanic string, i.e 

"STR_XXXX    :{BLACK}No mechanics hired".

Then, in src\openrct2\localisation\string_ids.h, at the end of the file, add the string identifier using the number you used in the data\language file(s), i.e

"STR_NO_MECHANIC = XXXX,"

Then, in windows\ride.c, add the conditions for the string you want to display in the calling mechanic switch-case block, and set the stringId variable to your desired string identifier.  Then, in the stringId if-else statement, copy-paste the code that displays the code, and set the if conditional to the string identifier you want, i.e

if (stringId == STR_NO_MECHANIC) {
	gfx_draw_string_left_wrapped(dpi, NULL, x + 4, y, 280, stringId, COLOUR_BLACK);
}

**Comment by Davespx** [comment]
There is a method in sources/peep/peep.h that returns the number of staff. 
There is also this method: sint32 peep_is_mechanic(rct_peep *peep); in the same file.
Maybe we can traverse through the staff and use the peep_is_mechanic to get a head count of mechanics

**Comment by Voytella** [comment]
Added some different conditions for the RIDE_MECHANIC_STATUS_CALLING case in '/Sources/windows/ride.c'.
