### ISSUE TITLE
Deleting signs after copy/paste crashes game.

### ISSUE THREAD

**Issue by Voytella** [TheEntireCommunistManifesto/OpenRCT2#3]
OS: Windows 7
Version: 0.0.7
Build: f6f6d27

If you open up a park then build a sign and then copy and paste it onto another tile. Deleting either copied one or original one will cause the game to crash. It will still crash even if you dont use the tile inspector to delete the sign.

- [ n/a ] Reproducible in RCT2 (vanilla)?
- [ yes ] Multiplayer?

**Steps to reproduce:**
1. Open up any park
2. Build any sign on any path.
3. Open up tile inspector and click on the signs
4. Click Copy
5. Click Paste on any other tile
6. Delete either one of the signs, and the game will crash.

Original: https://github.com/OpenRCT2/OpenRCT2/issues/5261

**Comment by Voytella** [comment]
The main code for the signs is found in Sources/windows/sign.c
Never mind, that's just the code for the sign editing window, not the sign itself.

NOTE: There is commented-out code in Sources/windows/tile_inspector.c line 2115.

Other than that line, there is no other reference to "sign" in that file.

**Comment by Voytella** [comment]
[signOccurancesJustSign.txt](https://github.com/TheEntireCommunistManifesto/OpenRCT2/files/841887/signOccurancesJustSign.txt)
A list of all the occurrences of "sign" (excluding "design" and "assign") in the project.

**Comment by mwilmott2013** [comment]
Possible Idea for Bug: EXC_BAD_ACCESS Error: Means that the program is 
trying to talk to a nonexistant object.  Theory is that the program is 
trying to talk to the sign we deleted.

**Comment by Voytella** [comment]
L. 58 of /src/openrct2/paint/map_element/banner.c is the source of the crash.
uint32 base_id = (direction << 1) + banner_scenery->image;
The line fails because "banner_scenery" is null when it's data point "image" is trying to be accessed.
In line 49, the assignment of "banner_scenery" is made based upon the contents of the "gBanners" array, which appears to be empty at the time of the assignment, thus assigning NULL to "banner_scenery".

**Comment by Voytella** [comment]
Thinking "gBanners" was a list of all the banners, we created two separate pairs of signs and deleted one sign, but "gBanners" was still empty. Now we think "gBanners" might be a list of all of the copies of a sign.

**Comment by Voytella** [comment]
It's looking like "gBanners" IS a list of all of the copies, because the page for OpenRCT2 says that the maximum number of banners is unknown, and "gBanners" only has 256 elements.

**Comment by Voytella** [comment]
The entries for gBanners are assigned in game_command_place_banner method in "/src/openrct2/world/map.c". Maybe something strange is happening there? It is also important to investigate where the entries of "gBanners" are removed.

**Comment by Voytella** [comment]
The game does not crash when the sign is deleted via the tile inspector rather than just the right-click menu.

**Comment by Voytella** [comment]
Exiting the banner_paint function when the banner_scenery object is null allows for the deletion of the sign without a crash. However, both signs are deleted and a refund is only given by one. This implies that the actual problem is that the copy and original are treated as one.

**Comment by Davespx** [comment]
Both signs are the same thing. 
I read that the game natively does not support copy/paste. The copy/paste feature is a from the tile inspector in debugging tools. I looked into the tile inspector copy/paste methods in tile_inspector.c and found that there is only an assignment of pointers, suggesting that both pointers (pasted and copied) point to the same memory. 
I'm looking into ways to modify the paste method so that it will create a new banner based from the copied one. Which will replace the pointer assignment operation.

**Comment by Voytella** [comment]
When the tile inspector is used to paste a copied item, the item is not bought in game; it acts like a ghost object of the original. Therefore, the behavior when the phantom signs are all deleted in the normal game (not the tile inspector), the behavior seen is expected. The tile inspector should not be used in a normal game, which is where this problem would occur.

For now, I've kept the line that prevents a crash by exiting the banner_paint function in Sources/paint/map_element/banner.c when the banner_scenery object is null.
